name: weighmywaterbottle
description: A new Flutter project.

version: 0.0.1+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Blocs
  flutter_bloc: 7.0.0

  # Save local variables
  shared_preferences: 2.0.6

  # Connectivity check
  connectivity_plus: 1.1.0

  # Firebase Core
  firebase_core: ^1.11.0

  # Firebase Authentication
  firebase_auth: ^3.3.5

  # Firebase Analytics
  firebase_analytics: ^9.0.5

  # Firebase Database
  firebase_database: ^9.0.5

  # Firebase CrashAnalytics
  firebase_crashlytics: ^2.4.5

  # For Accessing Google Fit API
  health: ^3.4.3

  # Change Notifier Providers
  # keep it 5.0.0 because flutter bloc depends on it
  provider: 5.0.0

  # Confetti
  confetti: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  # Launch icons
  flutter_launcher_icons: 0.9.0

  # Splash screen
  flutter_native_splash: 1.1.8+4


# flutter pub run flutter_launcher_icons:main
flutter_icons:
  image_path_android: lib/assets/logo/logo.png
  image_path_ios: lib/assets/logo/logo.png
  android: true
  ios: true

# flutter pub pub run flutter_native_splash:create
flutter_native_splash:
  color: "000000"
  android_disable_fullscreen: true


flutter:
  uses-material-design: true

  assets:
    - lib/assets/